# -*- coding: utf-8 -*-
"""ocr_calcs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hs6tm6Ur75bGns688EdVlO7Dan3kkX6B
"""

import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO

st.set_page_config(page_title="Outstanding Claims Reserve (OCR) Calculator", layout="wide")

# ---------- CUSTOM CSS (African Actuarial Consultants theme) ----------
st.markdown("""
<style>
    /* Global */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Calisto MT', serif;
        font-size: 11pt;
    }
    /* Header / Navigation */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        border-bottom: 3px solid #D4AF37;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
        transition: color 0.3s;
    }
    .nav-links a:hover {
        color: #D4AF37;
    }
    /* Hero Section */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #333333 100%);
        color: #FFFFFF;
        padding: 2rem 2rem;
        text-align: center;
        border-bottom: 3px solid #D4AF37;
    }
    .hero h1 {
        color: #D4AF37;
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
    }
    .hero p {
        font-size: 1.2rem;
        max-width: 800px;
        margin: 0 auto;
    }
    /* Main container */
    .main-container {
        max-width: 1400px;
        margin: 2rem auto;
        padding: 0 2rem;
    }
    /* Cards */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #D4AF37;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .card h3 {
        color: #D4AF37;
        margin-top: 0;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 0.5rem;
    }
    /* Footer */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #D4AF37;
        margin-top: 3rem;
    }
    .footer a {
        color: #D4AF37;
        text-decoration: none;
    }
    /* Streamlit element overrides */
    .stButton > button, .stDownloadButton > button {
        background-color: #D4AF37;
        color: #000000;
        border: none;
        border-radius: 4px;
        font-weight: bold;
        padding: 0.5rem 1rem;
        transition: all 0.3s;
    }
    .stButton > button:hover, .stDownloadButton > button:hover {
        background-color: #B8960F;
        color: #FFFFFF;
    }
    .stFileUploader {
        border: 2px dashed #D4AF37;
        border-radius: 5px;
        padding: 1rem;
    }
    .stMultiSelect [data-baseweb="select"] {
        border: 1px solid #D4AF37;
        border-radius: 4px;
    }
    .dataframe {
        border: 1px solid #D4AF37;
        border-radius: 8px;
        overflow: hidden;
    }
</style>
""", unsafe_allow_html=True)

# ---------- Header ----------
st.markdown("""
<div class="header">
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Services</a>
        <a href="#">Tools</a>
        <a href="#">Contact</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Hero ----------
st.markdown("""
<div class="hero">
    <h1>Outstanding Reserve (OCR) Calculator</h1>
    <p>Upload your data (CSV). The app groups by 'Line_Of_Business' and sums the selected numeric columns to produce a downloadable Outstanding Claims Reserve report.</p>
</div>
""", unsafe_allow_html=True)

# ---------- Main Container ----------
st.markdown('<div class="main-container">', unsafe_allow_html=True)

# Client name input
client_name = st.text_input("Client Name (for file name)", value="Client").strip()

# File uploader
uploaded_file = st.file_uploader("Choose a CSV file", type="csv")

if uploaded_file is not None:
    try:
        # Handle encoding
        try:
            df = pd.read_csv(uploaded_file, encoding='utf-8')
        except UnicodeDecodeError:
            uploaded_file.seek(0)
            df = pd.read_csv(uploaded_file, encoding='cp1252')
            st.warning("File read with Windows‑1252 encoding. For best results, save your CSV as UTF‑8.")

        # Drop any 'Unnamed' columns (common in Excel exports)
        columns_to_drop = [col for col in df.columns if col.startswith('Unnamed:')]
        if columns_to_drop:
            df = df.drop(columns=columns_to_drop)
            st.info(f"Dropped {len(columns_to_drop)} unnamed column(s).")

        # Check if 'Line_Of_Business' exists
        if 'Line_Of_Business' not in df.columns:
            st.error("The CSV must contain a column named 'Line_Of_Business'.")
        else:
            # Identify numeric columns
            numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
            # Remove 'Line_Of_Business' if it's numeric (unlikely but safe)
            if 'Line_Of_Business' in numeric_cols:
                numeric_cols.remove('Line_Of_Business')

            if not numeric_cols:
                st.error("No numeric columns found to sum.")
                st.stop()

            # Multi-select for columns to include
            st.markdown("Select Columns to Include in OCR")
            selected_cols = st.multiselect(
                "Choose the numeric columns you want to sum by Line of Business:",
                options=numeric_cols,
                default=numeric_cols[:min(5, len(numeric_cols))]  # default first few
            )

            if not selected_cols:
                st.warning("Please select at least one numeric column.")
                st.stop()

            # Group by Line_Of_Business and sum only selected columns
            grouped = df.groupby('Line_Of_Business')[selected_cols].sum().reset_index()

            # Display results in a card
            with st.container():
                st.markdown('<div class="card">', unsafe_allow_html=True)
                st.markdown("Outstanding Reserve by Line of Business")
                st.dataframe(grouped, use_container_width=True)

                # Prepare Excel download
                output = BytesIO()
                with pd.ExcelWriter(output, engine='openpyxl') as writer:
                    grouped.to_excel(writer, index=False, sheet_name='OCR')
                output.seek(0)

                # Build filename with client name
                safe_client = "".join(c for c in client_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
                if safe_client:
                    file_name = f"{safe_client}_Outstanding_Reserve.xlsx"
                else:
                    file_name = "Outstanding_Reserve.xlsx"

                st.download_button(
                    label="Download Excel Report",
                    data=output,
                    file_name=file_name,
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )
                st.markdown('</div>', unsafe_allow_html=True)

    except Exception as e:
        st.error(f"An error occurred: {e}")

st.markdown('</div>', unsafe_allow_html=True)  # close main-container

# ---------- Footer ----------
st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved. | <a href="#">Privacy</a> | <a href="#">Terms</a></p>
    <p style="margin-top: 0.5rem; font-size: 0.9rem;">Powered by Streamlit</p>
</div>
""", unsafe_allow_html=True)

